/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SchedulesController_findAll"];
        put?: never;
        post: operations["SchedulesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/unavailable-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SchedulesController_findUnavailableDates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SchedulesController_findOne"];
        put: operations["SchedulesController_update"];
        post?: never;
        delete: operations["SchedulesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/submit-for-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_submitForApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulesController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{scheduleId}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ScheduleShiftsController_findAll"];
        put?: never;
        post: operations["ScheduleShiftsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShiftsController_findOne"];
        put: operations["ShiftsController_update"];
        post?: never;
        delete: operations["ShiftsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{shiftId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShiftAssignmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AssignmentsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssignmentsController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssignmentsController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts/{shiftId}/assignment-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShiftAssignmentProposalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignment-proposals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AssignmentProposalsController_update"];
        post?: never;
        delete: operations["AssignmentProposalsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignment-proposals/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssignmentProposalsController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignment-proposals/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssignmentProposalsController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Email address used as the login identifier.
             * @example test-employee@example.com
             */
            username: string;
            /**
             * @description Account password (equals the email address for seeded dev accounts).
             * @example test-employee@example.com
             */
            password: string;
        };
        CreateScheduleDto: {
            label?: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            timeZone: string;
        };
        ScheduleEntity: {
            label: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            timeZone: string;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED";
            rejectionReason: string | null;
            shifts: components["schemas"]["ShiftEntity"][];
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        AssignmentProposalEntity: {
            shiftId: string;
            shift: components["schemas"]["ShiftEntity"];
            employeeId: string;
            employee: components["schemas"]["UserEntity"];
            message: string | null;
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        UserEntity: {
            password: string;
            firstName: string;
            lastName: string;
            emailAddress: string;
            roles: ("EMPLOYEE" | "MANAGER" | "APPROVER")[];
            assignments: components["schemas"]["AssignmentEntity"][];
            proposals: components["schemas"]["AssignmentProposalEntity"][];
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        AssignmentEntity: {
            shiftId: string;
            shift: components["schemas"]["ShiftEntity"];
            employeeId: string;
            employee: components["schemas"]["UserEntity"];
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "DECLINED";
            declineReason: string | null;
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ShiftEntity: {
            scheduleId: string;
            schedule: components["schemas"]["ScheduleEntity"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            requiredHeadcount: number;
            assignments: components["schemas"]["AssignmentEntity"][];
            proposals: components["schemas"]["AssignmentProposalEntity"][];
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ScheduleViewDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
            label: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            timeZone: string;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED";
            rejectionReason: string | null;
            /** @description Sum of requiredHeadcount across every shift in the schedule. */
            totalRequiredHeadcount: number;
            /** @description Assignments that have not been declined, across every shift. */
            totalFilledCount: number;
            /** @description Assignments in the ACCEPTED state, across every shift. */
            totalAcceptedCount: number;
        };
        PaginationMetaDto: {
            /** @description Total number of matching rows across all pages. */
            total: number;
            /** @description 1-based page number that was returned. */
            page: number;
            /** @description Maximum number of items per page. */
            limit: number;
            /** @description Total number of pages for the current page size (0 when there are no rows). */
            totalPages: number;
        };
        PaginatedSchedulesDto: {
            items: components["schemas"]["ScheduleViewDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UnavailableDatesDto: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        UpdateScheduleDto: {
            label?: string | null;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            timeZone?: string;
        };
        RejectScheduleDto: {
            rejectionReason: string;
        };
        UserResponseDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
            firstName: string;
            lastName: string;
            roles: ("EMPLOYEE" | "MANAGER" | "APPROVER")[];
        };
        CreateShiftDto: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            requiredHeadcount: number;
        };
        EmployeeRefDto: {
            id: string;
            firstName: string;
            lastName: string;
        };
        AssignmentViewDto: {
            id: string;
            employeeId: string;
            employee: components["schemas"]["EmployeeRefDto"];
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "DECLINED";
            declineReason: string | null;
        };
        ProposalViewDto: {
            id: string;
            employeeId: string;
            employee: components["schemas"]["EmployeeRefDto"];
            message: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ShiftBoardViewDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: date-time */
            deletedAt: string | null;
            scheduleId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            requiredHeadcount: number;
            /** @description Assignments that have not been declined. */
            filledCount: number;
            /** @description Number of open assignments. */
            spotsRemaining: number;
            assignments: components["schemas"]["AssignmentViewDto"][];
            proposals: components["schemas"]["ProposalViewDto"][];
        };
        UpdateShiftDto: {
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            requiredHeadcount?: number;
        };
        CreateAssignmentDto: {
            /** Format: uuid */
            employeeId: string;
        };
        DeclineAssignmentDto: {
            declineReason: string;
        };
        CreateAssignmentProposalDto: {
            message: string;
        };
        UpdateAssignmentProposalDto: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulesController_findAll: {
        parameters: {
            query: {
                status?: "DRAFT" | "IN_REVIEW" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED";
                mine?: boolean;
                page: number;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSchedulesDto"];
                };
            };
        };
    };
    SchedulesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_findUnavailableDates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnavailableDatesDto"][];
                };
            };
        };
    };
    SchedulesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleViewDto"];
                };
            };
        };
    };
    SchedulesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_submitForApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    SchedulesController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectScheduleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntity"];
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                availableFor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_findMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    ScheduleShiftsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftBoardViewDto"];
                };
            };
        };
    };
    ScheduleShiftsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShiftDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ShiftsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ShiftsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShiftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ShiftsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftAssignmentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shiftId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AssignmentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentsController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AssignmentsController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineAssignmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ShiftAssignmentProposalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shiftId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentProposalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentProposalEntity"];
                };
            };
        };
    };
    AssignmentProposalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssignmentProposalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentProposalEntity"];
                };
            };
        };
    };
    AssignmentProposalsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentProposalsController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentProposalsController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
